
paths:

  /users:
    GET:
      controller: users-controller
      operation: usersList
      response:
        - 200
        - 400
        - 404
    POST:
      controller: users-controller
      operation: usersCreate
      params:
        data: 
          name:
            type: string
          email:
            type: string
      response:
        - 201
        - 400
        - 404

  /users/:id:
    GET:
      controller: users-controller
      operation: usersGet
      params:
        path: 
          id:
      response:
        - 200
        - 400
        - 404
    PATCH:
      controller: users-controller
      operation: usersUpdate
      params:
        path: 
          id:
        data: 
          name:
            type: string
          email:
            type: string
      response:
        - 202
        - 400
        - 404
    DELETE:
      controller: users-controller
      operation: usersDelete
      params:
        path: 
          id:
        data: 
          name:
            type: string
          email:
            type: string
      response:
        - 202
        - 400
        - 404